### ISSUE TITLE
@function(cost=?) cannot be used inside of a class to decorate its functions

### ISSUE THREAD

**Issue by shinawy** [egraphs-good/egglog-python#229]
I can't use the decorator `@function` inside of a class while using `self` or `cls` as the parameter of the function decorated. The following example gives an error. 

```python
import egglog as el 

# @dataclass
class Num(el.Expr):
    def __init__(self, value: el.i64Like) -> None:
        ...

    # This works
    @classmethod
    def var(cls, name: el.StringLike) -> Num:
        ...
     
    # this does not work
    @function (cost=10)
    def __add__(cls, other: Num) -> Num:
        ...

     # this does not work
    @function (cost=10)
    def __add__(self, other: Num) -> Num:
        ...
```

Is this considered an issue? If no, is there another way to set costs and other attributes for functions without using the `function` decorator?

**Comment by saulshanabrook** [comment]
Please use the `@method` decorator instead in classes!

**Comment by shinawy** [comment]
Great, thank you so much.
